name: Qodana
on:
  push:
    branches:
      - main
    paths:
    - 'server/**'
    - '.github/workflows/secure-notes-functions.yml'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Navigate to server directory'
        run: cd server
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
