name: Deploy Secure Notes Site

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SECRET_NOTES_SITE_API_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "/client"
          api_location: "" 
          output_location: "dist" 